### ISSUE TITLE
数据获取

### ISSUE THREAD

**Issue by zhangheyi-1** [ywjawmw/ShenNong-TCM-Evaluation-BenchMark#1]
您好，请问测评数据怎么获取

**Comment by ywjawmw** [comment]
我们基于该数据集组织了中医知识推理与理解竞赛，第一轮的数据已经公开。
[TCMBench中医知识理解与推理能力评测——参数高效微调赛道](https://tianchi.aliyun.com/competition/entrance/532204)
[TCMBench中医知识理解与推理能力评测——不微调赛道](tianchi.aliyun.com/competition/entrance/532199?spm=a2c22.12281976.0.0.67652fdcTVjoU4)

**Comment by mazai-xiangji** [comment]
你好，请问完整的测试数据什么时候会公开

**Comment by ywjawmw** [comment]
第二轮的数据预计8月初公开

**Comment by xansar** [comment]
> 第二轮的数据预计8月初公开

数据开源按照哪种开源License呢？

**Comment by ywjawmw** [comment]
可以进行科学研究

**Comment by ywjawmw** [comment]
您好，感谢关注我们的工作，目前我们的数据集可以进行公开的科学研究，目前还未开放商业用途。

**Comment by zhu-code** [comment]
请问数据还公布吗

**Comment by Nancyershui** [comment]
> 我们基于该数据集组织了中医知识推理与理解竞赛，第一轮的数据已经公开。 [TCMBench中医知识理解与推理能力评测——参数高效微调赛道](https://tianchi.aliyun.com/competition/entrance/532204) [TCMBench中医知识理解与推理能力评测——不微调赛道](tianchi.aliyun.com/competition/entrance/532199?spm=a2c22.12281976.0.0.67652fdcTVjoU4)

请问数据集现在还方便开放吗
